"""adicionar_coluna_descricao_na_tabela_servico

Revision ID: 9182368389d7
Revises: 00f17853c1c4
Create Date: 2026-02-20 17:47:18.591756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9182368389d7'
down_revision: Union[str, Sequence[str], None] = '00f17853c1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'descricao')
    # ### end Alembic commands ###
